Repository lcomment/development-recipes, pull requests merged in 2022-07, with the labels that each got.

#2 👆add: README
  README.md
Labels: add

#8 👆add: reademe 수정
  README.md
Labels: add👆

#10 💡create: 포트포워딩 이론 작성
  Computer Science/Network/port-forwarding.md
  README.md
  resources/port1.png
Labels: add👆, create💡

#13 💡create: express 기본 이론 작성
  README.md
  Web-Node/Express js/express.md
Labels: add👆, create💡

#15 💡create: OAuth 2.0 이론 작성
  README.md
  Web/OAuth2.0.md
  resources/web/oauth1.png
  resources/web/oauth2.png
  resources/web/oauth3.png
  resources/web/oauth4.png
Labels: add👆, create💡

#20 👆add: mst, kruskal 목록 추가
  README.md
Labels: add👆
