Repository lcomment/development-recipes, pull requests merged in 2022-10, with the labels that each got.

#77 🛠revise: 서론 수정
  Computer Science/Algorithm/combination.md
Labels: revise🛠

#78 💡create: 순열 이론 작성
  Computer Science/Algorithm/combination.md
  Computer Science/Algorithm/permutation.md
Labels: create💡

#79 PR: docs to main
  README.md
  Web/restApi.md
Labels: revise🛠

#80 💡create: PUT과 PATCH 이론 작성
  Web/putNpatch.md
Labels: create💡

#81 PR: docs to main
  Cloud and DevOps/git/github.md
  README.md
Labels: add👆

#82 PR: lcomment to main
  Computer Science/SW Engineering/mvc.md
  README.md
  resources/swEngineering/mvc1.png
Labels: add👆, create💡, style🎀

#83 🛠revise: mvc 이점 수정
  Computer Science/SW Engineering/mvc.md
Labels: revise🛠

#84 PR: lcomment to main
  Language/Python/selenium.md
  resources/python/selenium1.png
Labels: create💡, style🎀

#85 PR: lcomment to main
  Computer Science/Algorithm/ccw.md
  README.md
Labels: add👆, create💡

#86 PR: lcomment to main
  Computer Science/Database/dbDesign.md
  Computer Science/Database/rdb.md
  resources/db/design.png
  resources/db/rdb.png
Labels: create💡, style🎀

#88 PR: lcomment to main
  Computer Science/Database/key.md
  Computer Science/Network/osi.md
  resources/network/osi.png
Labels: create💡, style🎀

#89 👆add: DB 관련 작성글 추가
  README.md
Labels: add👆

#90 💡create: block/nonblock, sync/async 이론 작성
  Computer Science/Network/blockNnonNsyncNasync.md
  resources/network/2by2matrix.png
Labels: create💡, style🎀

#91 💡create: 전송계층 프로토콜 이론 작성
  Computer Science/Network/tcpNudp.md
  resources/network/tcp.png
  resources/network/udp.png
Labels: create💡, style🎀

#92 💡create: 네트워크 관련 이론 작성
  Computer Science/Network/3wayN4way.md
  Computer Science/Network/loadBalancing.md
  resources/network/3way.jpg
  resources/network/4way.jpg
  resources/network/loadbalancing.png
Labels: create💡, style🎀

#93 🛠revise: 오타 수정
  Computer Science/Network/3wayN4way.md
Labels: revise🛠

#94 👆add: 네트워크 목록 추가
  README.md
Labels: add👆

#95 💡create: HTPP와 HTTPS 이론 작성
  Computer Science/Network/httpNhttps.md
  resources/network/http.png
Labels: create💡, style🎀

#96 💡create: 웹 동작원리 이론 작성
  Web/web.md
  resources/web/web.png
Labels: create💡, style🎀

#97 💡create: 쿠키와 세션 이론 작성
  Web/cookieNsession.md
Labels: create💡

#98 👆add: 웹 카테고리 목록 추가
  README.md
Labels: add👆

#99 🎀style: readme 수정
  README.md
Labels: style🎀

#100 💡create: JWT 이론 작성
  Web/jwt.md
  resources/web/jwt.png
  resources/web/jwtProcess.png
Labels: create💡, style🎀

#102 💡create: Spring MVC 이론 작성
  Web-Spring/springMvc.md
  resources/spring/springMVC.png
Labels: create💡, style🎀

#103 💡create: forward와 redirect 이론 작성
  Web/redirectNforward.md
  resources/web/forward.png
  resources/web/redirect.png
Labels: create💡, style🎀

#104 👆add: web, spring 목록 추가
  README.md
Labels: add👆

#105 💡create: Spring과 Spring Boot 차이점 작성
  Web-Spring/springNboot.md
Labels: create💡

#106 💡create: Spring REST Docs 이론 작성
  Web-Spring/Spring REST Docs/springRestDocs.md
  resources/spring/RESTDocs/springRestDoc.png
Labels: create💡, style🎀

#107 🛠revise: Spring 목록 변경
  README.md
Labels: revise🛠

#87 💡create: typescript의 clean_code
  Language/Typescript/typescript_cleancode.md
Labels: create💡

#110 💡create: 그리디 알고리즘 작성
  Computer Science/Algorithm/greedy.md
  resources/algorithm/greedy1.png
  resources/algorithm/greedy2.png
Labels: create💡, style🎀

#111 💡create: devops 관련 이론 작성
  Cloud and DevOps/aws/autoScaling.md
  Cloud and DevOps/aws/rds.md
  Cloud and DevOps/terraform/terraform.md
Labels: create💡

#112 👆add: devops 및 알고리즘 목록 추가
  README.md
Labels: add👆

#113 👆add: 오토스케일링 목록 추가
  README.md
Labels: add👆

#114 💡create: Git-Flow 이론 작성
  Cloud and DevOps/git/gitflow.md
  resources/git/gitflow.png
Labels: create💡, style🎀

#115 👆add: 깃플로우 목록 추가
  Cloud and DevOps/git/gitflow.md
  README.md
Labels: revise🛠, add👆

#116 💡create: Request 객체의 3가지 메서드 작성
  Web/requestObject.md
Labels: create💡

#117 💡create: SpringFox의 Swagger 이론 작성
  Web-Spring/swagger.md
Labels: create💡

#118 PR: lcomment to main
  README.md
  Web-Spring/Spring MVC/dao_dto_vo.md
  Web-Spring/Spring MVC/springMvc.md
Labels: create💡, style🎀

#119 🛠revise: 경로 변경
  README.md
Labels: revise🛠

#120 🛠revise: image path 변경
  Web-Spring/Spring MVC/springMvc.md
Labels: revise🛠

#121 🛠revise: join 이론 수정 및 추가
  Computer Science/Database/SQL/join.md
Labels: revise🛠

#122 💡create: INDEX 이론 작성
  Computer Science/Database/index.md
Labels: create💡

#123 👆add: DB 관련 목록 추가
  README.md
Labels: add👆
