Repository lcomment/development-recipes, pull requests merged in 2022-11, with the labels that each got.

#124 💡create: LIS 이론 작성
  Computer Science/Algorithm/lis.md
  README.md
Labels: add👆, create💡

#125 💡create: rdb 네이밍 규칙 작성
  Computer Science/Database/rdbNaming.md
  README.md
Labels: add👆, create💡

#126 테스트 코드 작성법 추가
  Web-Spring/testCode.md
Labels: add👆, create💡

#128 PR: docs to main
  Language/Java/set.md
  Language/Java/stream.md
  README.md
  Web-Spring/testCode.md
Labels: add👆, create💡, style🎀

#129 👆add: spring파트 test 목록 추가
  README.md
Labels: add👆

#130 🎀style: Programming 관련 카테고리 추가
  Programming/Object-Orientation/ood.md
  Programming/Object-Orientation/oop.md
  Programming/Test/tdd.md
  README.md
Labels: style🎀

#131 💡create: 테스트와 테스트 코드 관련 이론 작성
  Programming/Test/test.md
  resources/programming/Test/test.png
Labels: create💡

#133 💡create: Process와 Thread 이론 작성
  Computer Science/Operating System/process_thread.md
  resources/os/process_thread.png
Labels: create💡, style🎀

#134 💡create: 프로세스 주소영역과 PCB 관련 이론 작성
  Computer Science/Operating System/pas_pcb.md
  resources/os/pap.png
  resources/os/pcb.png
Labels: create💡, style🎀

#136 💡create: 데드락 이론 작성
  Computer Science/Operating System/deadlock.md
Labels: create💡

#137 👆add: OS 관련 목록 추가
  README.md
Labels: add👆

#139 🎀style: 목록 수정
  Language/Java/aboutStream.md
  README.md
Labels: style🎀

#140 💡create: Semaphore와 Mutex 이론 작성
  Computer Science/Operating System/semaphore_mutex.md
Labels: create💡

#141 💡create: Race Condition 관련 이론 작성
  Computer Science/Operating System/raceCondition.md
Labels: create💡

#143 👆add: DB 관련 목록 추가
  README.md
Labels: add👆

#144 💡create: DDL, DML, DCL, TCL 이론 작성
  Computer Science/Database/SQL/ddl_dml_dcl_tcl.md
  README.md
Labels: add👆, create💡

#145 💡create: Spring devtools 이론 작성
  README.md
  Web-Spring/devtools.md
  resources/spring/liveReload.png
Labels: revise🛠, create💡, style🎀

#146 💡create: 트랜잭션 이론 작성
  Computer Science/Database/transaction.md
Labels: create💡

#147 💡create: sql 기본 문법 작성
  Computer Science/Database/sqlGrammar.md
Labels: create💡

#148 🛠revise: 디렉토리 변경
  Computer Science/Database/SQL/sqlGrammar.md
Labels: revise🛠

#149 💡create: 자료 구조 관련 이론 작성
  Computer Science/Data Structure/list.md
  Computer Science/Data Structure/tree.md
  resources/dataStructure/tree/tree.png
Labels: create💡, style🎀

#150 🛠revise: 목록 재정렬
  README.md
Labels: revise🛠

#151 💡create: 이진 트리 이론 작성
  Computer Science/Data Structure/binaryTree.md
Labels: create💡

#152 💡create: B-Tree 관련 이론 작성
  Computer Science/Data Structure/bTree.md
  Computer Science/Data Structure/binaryTree.md
Labels: add👆, create💡

#153 🛠revise: 자료구조 목록 경로 변경
  README.md
Labels: revise🛠

#154 💡create: ecs ecr 이론 작성
  Cloud and DevOps/aws/ecs_ecr.md
  resources/aws/ecs.png
Labels: create💡, style🎀

#155 💡create: 자바 버전별 차이 정리
  Language/Java/javaVersion.md
Labels: create💡

#156 👆add: 목록 추가
  README.md
Labels: add👆

#158 💡create: CICD 이론 작성
  Cloud and DevOps/cicd.md
Labels: create💡

#159 👆add: 목록 추가
  README.md
Labels: add👆

#160 💡create: Docker 기본 이론 작성
  Cloud and DevOps/docker/docker.md
  resources/docker/vm_container.png
Labels: create💡

#161 💡create: CORS 이론 작성
  Web/cors.md
Labels: create💡
